# Generated by Django 5.2.7 on 2026-05-01 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0017_notification_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='fr', max_length=20)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('dashboard_compact', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='admin_dashboard.employee')),
            ],
        ),
    ]
