# Generated by Django 5.2.7 on 2026-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_room_timetablesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('payment', 'Payment'), ('timetable', 'Timetable'), ('system', 'System'), ('warning', 'Warning')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object', models.CharField(blank=True, help_text='Optional label like student name, formation title, invoice ref, etc.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
