# Generated by Django 5.2.7 on 2026-04-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='program',
        ),
    ]
