# Generated by Django 5.2.7 on 2026-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_schoolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school/'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_name',
            field=models.CharField(default='Centre de formation Jouri', max_length=200),
        ),
    ]
