# Generated by Django 5.2.7 on 2026-05-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0018_employeepayment_invoice_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dossier_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='formation_type',
            field=models.CharField(blank=True, choices=[('12mois', '12 mois'), ('4mois', '4 mois'), ('atelier', 'Atelier')], default='', max_length=20),
        ),
    ]
