# Generated by Django 5.2.7 on 2026-05-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0019_student_dossier_submitted_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='formations/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_dashboard.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Image de formation',
                'verbose_name_plural': 'Images de formation',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormationObjectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300, verbose_name='Objectif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='admin_dashboard.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Objectif',
                'verbose_name_plural': 'Objectifs',
                'ordering': ['order'],
            },
        ),
    ]
